# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19418b580284c7dc36ee586d33c8d6615294f56ce6d07ed937461fc19cebefb7e295672360e2b5527bb5b82c78b80e191b8477cfb8043b225dc27cf29b324d75

test:
  secret_key_base: 471f01c0a1692300d198c2c348d21d0a477fae4bba373ef32aa0b31b5a92be19677534a21635da937ca570b413d20f53eeef8202b3265be47e7bbb9636d40c72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
